{% set name = "nebari" %}
{% set version = "2023.11.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nebari-{{ version }}.tar.gz
  sha256: 974fb5b77122974323c28b65b0e9a59610b4a6397b3ea622250d385f5a4d64a7

build:
  number: 1
  noarch: python
  entry_points:
    - nebari = nebari.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - setuptools-scm
    - hatchling
    - hatch-vcs
  run:
    - __unix
    - python >=3.8,<4.0
    - auth0-python ==4.4.2
    - azure-identity ==1.12.0
    - azure-mgmt-containerservice ==26.0.0
    - azure-mgmt-resource ==23.0.1
    - bcrypt ==4.0.1
    - boto3 ==1.28.40
    - cloudflare ==2.11.7
    - python-kubernetes ==27.2.0
    - pluggy ==1.3.0
    - prompt-toolkit ==3.0.36
    - pydantic ==1.10.12
    - pynacl ==1.5.0
    - python-keycloak ==3.3.0
    - questionary ==2.0.0
    - requests-toolbelt ==1.0.0
    - rich ==13.5.1
    - ruamel.yaml ==0.17.32
    - typer ==0.9.0
    - packaging ==23.2

test:
  imports:
    - nebari
  commands:
    - pip check
    - nebari --help
    - if [[ $(nebari --version) != {{ version }} ]]; then exit 1; else exit 0; fi
  requires:
    - pip

about:
  home: https://github.com/nebari-dev/nebari
  summary: A Jupyter and Dask-powered open source data science platform.
  dev_url: https://github.com/nebari-dev/nebari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dcmcand
    - viniciusdc
    - iameskild
