{% set name = "nebari" %}
{% set version = "2024.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nebari-{{ version }}.tar.gz
  sha256: 825795f45da7f91f0532746e5098175a9362bf6b60d9937c5c02c0ac0796a879

build:
  number: 0
  noarch: python
  entry_points:
    - nebari = nebari.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - setuptools-scm
    - hatchling
    - hatch-vcs
  run:
    - __unix
    - python >=3.8,<4.0
    - auth0-python
    - azure-identity
    - azure-mgmt-containerservice
    - azure-mgmt-resource
    - bcrypt
    - boto3
    - cloudflare
    - python-kubernetes
    - pluggy
    - prompt-toolkit
    - pydantic
    - pynacl
    - python-keycloak
    - questionary
    - requests-toolbelt
    - rich
    - ruamel.yaml
    - typer
    - packaging

test:
  imports:
    - nebari
  commands:
    - pip check
    - nebari --help
    - if [[ $(nebari --version) != {{ version }} ]]; then exit 1; else exit 0; fi
  requires:
    - pip

about:
  home: https://github.com/nebari-dev/nebari
  summary: A Jupyter and Dask-powered open source data science platform.
  dev_url: https://github.com/nebari-dev/nebari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelovilla
    - dcmcand
    - viniciusdc
