{% set name = "nebari" %}
{% set version = "2023.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nebari-{{ version }}.tar.gz
  sha256: 309f4ebf0a9fafdef2d85d34b058685da476ccf882e159261a5ea55ab0b04b29

build:
  number: 0
  noarch: python
  entry_points:
    - nebari = _nebari.cli.main:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - setuptools-scm
    - hatchling
    - hatch-vcs
  run:
    - __unix
    - python >=3.8,<4.0
    - auth0-python ==4.0.0
    - azure-identity ==1.12.0
    - azure-mgmt-containerservice ==19.1.0
    - bcrypt ==3.2.2
    - boto3 ==1.26.78
    - cloudflare ==2.11.1
    - pydantic ==1.10.5
    - pynacl ==1.5.0
    - python-keycloak ==2.12.0
    - python-kubernetes ==26.1.0
    - questionary
    - requests-toolbelt <0.10.0,>=0.9.1
    - rich ==12.6.0
    - ruamel.yaml ==0.17.21
    - typer ==0.7.0
    - requests-toolbelt ==0.9.1

test:
  imports:
    - nebari
  commands:
    - pip check
    - nebari --help
    - if [[ $(nebari --version) != {{ version }} ]]; then exit 1; else exit 0; fi
  requires:
    - pip

about:
  home: https://github.com/nebari-dev/nebari
  summary: A Jupyter and Dask-powered open source data science platform.
  dev_url: https://github.com/nebari-dev/nebari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - viniciusdc
    - iameskild
